[package]
name = "titan-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0.90", features = ["full"] }
proc-macro-crate = "3.2.0"
anyhow = "1.0.94"
nanoid = "0.4.0"
