[package]
name = "titan-cli"
version = "0.1.0"
edition = "2021"

[dependencies.colored]
version = "2.1.0"

[dependencies.clap]
version = "4.5.19"
features = ["derive"]

[dependencies.include_dir]
version = "0.7.4"
